[build]
  command = "npm run build"

<<<<<<< HEAD

cat <<EOF > netlify.toml
[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"
EOF
=======
[[plugins]]
  package = "@netlify/plugin-nextjs"
>>>>>>> f502b10 (Fix broken netlify.toml)
